sudo: false
language: ruby
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
before_install:
  - gem install bundler -v 1.16.1
  - gem install mailcatcher

install:
  - (cd coruro-ruby && bundle install --path vendor/bundle)

script: (cd coruro-ruby && bin/rake)

